using be.berghs.nils.eetfestijn.classes;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using System.Windows.Shapes;

namespace be.berghs.nils.eetfestijn.windows
{
    /// <summary>
    /// Interaction logic for DefineMenu.xaml
    /// </summary>
    public partial class DefineMenu : Window
    {
        public DefineMenu()
        {
            InitializeComponent();
            ProductsGrid.ItemsSource = App.mProductList.Products;

            ProductsGrid.AutoGeneratedColumns += ProductsGrid_AutoGeneratedColumns;
        }

        private void ProductsGrid_AutoGeneratedColumns(object sender, EventArgs e)
        {
            ProductsGrid.Columns[0].Width = new DataGridLength(1, DataGridLengthUnitType.Star);
        }

        private void Button_Click(object sender, RoutedEventArgs e)
        {
            this.Close();
        }
    }
}
